#version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload && ambelic upgrade head
    #env_file:
    #  - ./.env    
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME_REMOTE}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-db: